### ISSUE TITLE
How to expand the Available datasets of viirs/npp

### ISSUE THREAD

**Issue by NIAM12138** [dawhite/VCTK#11]
I'd download the GMTCO-VLSTO_npp.h5 data，I want to modify the LandSurfaceTempurature dataset and rewrite the data into files，but h5 file can't write. 
I use the function h5_putdata to put the new dataset into files, but the VIIRS Conversion Toolkit can't recognit the new dataset,so how can i use this tool to deal the new dataset?

**Comment by dawhite** [comment]
VCTK is intentionally designed to only work with the official products distributed by NOAA. I don't recommend doing what you are attempting to do. You have two options: 

1. Modify the existing LandSurfaceTempurature dataset, which should be possible. I'm not sure why you are running into an error.
2. Modify the lookup file that VCTK uses to parse the official products so your new dataset is accessible

Again, I don't recommend the second one and it's unsupported, so I can't help you troubleshoot, but if you want to attempt it, here's what you do:

Open the viirs_products.scsv file that is installed in ENVI in a text editor and find the VLSTO line (I think it's currently 56). It will look like this:

VLSTO;VIIRS-LST-EDR;VIIRS Land Surface Temperature EDR;750;0;0;0;0;0;0;0;0;None;0;0;0;2;1;LandSurfaceTemperature;LSTFactors;[]65532:65533;0

Assuming that you do not alter the NoData values in the LST dataset, modify that line to look like this:

VLSTO;VIIRS-LST-EDR;VIIRS Land Surface Temperature EDR;750;0;0;0;0;0;0;0;0;None;0;0;0;2;1;LandSurfaceTemperature,LandSurfaceTemperatureMod;LSTFactors,LSTFactorsMod;[]65532:65533,[]65532:65533;0

The new entries are each preceded by a comma. I made up the names "LandSurfaceTemperatureMod" and "LSTFactorsMod" so you will want to change those to the names you're using for both new entries. Make sure that you include the second copy of "[]65532:65533". **The entry names must be unique when compared to the original dataset**. If you run into issues creating a new factors entry, I recommend you download a tool like HDFView and look at how the original one is stored in the official file.

Save your changes and restart VCTK.
