### ISSUE TITLE
Question on VIIRS EDR data

### ISSUE THREAD

**Issue by nlbakker** [dawhite/VCTK#4]
Dear dawhite,

I've been using MCTK for a while and it works great (thanks for that!), now I'm trying to use VCTK, however I can't seem to get it to work with VIIRS EDR AOT data (GAERO-VAOOO; I'm getting the data from NOAA CLASS). When I try to specify the input file it gives me the error ''SDR/EDR/ARP products file can not be found''. Would you have any idea what might be the issue? Should the input file be in a specific directory? 

Thanks in advance!

**Comment by dawhite** [comment]
As outlined at the beginning of the user guide, you have to install both the vctk.sav and viirs_products.scsv file in the same folder. That should resolve the issue.

**Comment by nlbakker** [comment]
Ah, apologies, I thought I had, but it seems indeed the file went missing somewhere. That resolved it. Thanks!
