### ISSUE TITLE
WL variable undefined error in VIIRS Conversion Toolkit （VCTK v1.1.6）

### ISSUE THREAD

**Issue by Jefflywen** [dawhite/VCTK#5]
I'm selecting individual datasets (ie., Day Night Band products, SatelliteZenithAngle stored with the geolocation data ) to process in VIIRS Conversion Toolkit ( VCTK v1.1.6),  then I get the following error: variable undefined: WL.  I don't know where the WL variable should be defined or where it's used because of my operation.  Is there an  way to solve the problem?

![error](https://user-images.githubusercontent.com/38515888/38969244-db394e12-43c1-11e8-9ea9-2db548e8ecb7.png)

**Comment by dawhite** [comment]
Make sure you have VCTK correctly installed. Per the instructions in the user guide, you need to place both the .sav and the .scsv files in your save_add or extensions folder. If that isn't the issue, try downloading the file again. Sometimes corrupted files cause errors like that.
