### ISSUE TITLE
VCTK-1.1.6 /// a problem in processing VIIRS albedo(GMTCO-VISAO)

### ISSUE THREAD

**Issue by Reyhan-r** [dawhite/VCTK#6]
Dear Dr. White,

First of all, I would like to thank you for providing these great ENVI plugins. Now I'm trying to use the VCTK-1.1.6(the last version) to process the **_VIIRS albedo(GMTCO-VISAO)_** but the following error comes out:

Attempt to subscript IMG_IDX with I is out of range.
% Execution halted at: VIIRS_DATA_QUERY  380
%                      VCTK_EVENT         90
%                      WIDGET_PROCESS_EVENTS
%                      VIIRS_DATA_QUERY  380
%                      VCTK_EVENT         90
%                      WIDGET_PROCESS_EVENTS
%                      $MAIN$

I will appreciate you if you guide me in solving this problem because the result of all my research is depending on it.

Yours sincerely
Reyhaneh.R
2018-04-20

**Comment by dawhite** [comment]
That product isn't currently supported by VCTK. I've had a difficult time finding sample data to test compatibility. It won't be hard to add support if I have data to work with, but I won't be able to do that for several weeks.

**Comment by Reyhan-r** [comment]
I hope you get free time as soon as possible to add the support but for now that it's not possible for you ,which website or source of information do you recommend to get **Albedo, Radiation(short/long wave), Evaporation & Transpiration data**? The time period should cover from **2013** to **2017**.

**Comment by Reyhan-r** [comment]
I hope you get free time as soon as possible to add the support but for now that it's not possible for you ,which website or source of information do you recommend to get **Albedo, Radiation(short/long wave), Evaporation & Transpiration data ?** The time period should cover from **2013** to **2017**.

**Comment by dawhite** [comment]
My recommendation would be to switch from VIIRS to MODIS. There should be a variety of datasets for you to work with that span the temporal range you are interested in. And since your start date is 2013 and VISAO wasn't publicly released until 2014, MODIS is likely your only option if you want consistent data: https://earthdata.nasa.gov/
