### ISSUE TITLE
EDR I5 Brightness temperature values

### ISSUE THREAD

**Issue by JulieSokol** [dawhite/VCTK#8]
Dear dawhite,

I have a question concerning EDR data processing. I got I5 channel EDRs from NOAA CLASS and tried to convert them to brightness temperature GeoTiffs via VCTK. Pixel values vary around 9-10 which does not look like brightness temperatures. I tried to compare these results with SDR format (same image) and found out that SDRs give values around 250 which looks like true. What could be the problem with EDRs?

Thank you in advance,
Julia

**Comment by dawhite** [comment]
Which two specific products are you comparing? If you can provide an example filename for each product that would be helpful.

**Comment by JulieSokol** [comment]
Sure. Here are they:
1) SDR: GIMGO-SVI05_j01_d20200227_t0013136_e0018554_b11785_c20200522100953931098_nobc_ops.h5
2) EDR: GIGTO-VI5BO_j01_d20200227_t0013118_e0019020_b11785_c20200521202307432897_nobc_ops.h5

**Comment by dawhite** [comment]
That helped a lot--thank you. Looks like there was a change in how the scale and offset factors for brightness temperature datasets are stored in the Imagery Band EDR products. I have updated the plugin to address the issue. A new version, v.1.1.10, is now available under Releases: https://github.com/dawhite/VCTK/releases/tag/v1.1.10.

**Comment by JulieSokol** [comment]
It's fine now! Values seem realistic! Thank you for the update, dawhite!

**Comment by dawhite** [comment]
You're welcome!
